import { inter } from "@/util/font";
import "./globals.css";

export const metadata = {
  title: "Student Management System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
