# Generated by Django 5.0 on 2023-12-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='firstName',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='lastName',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='matricNo',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
