const data = [
  {
    id: 1,
    firstName: "Ellen",
    lastName: "Griffith",
    matricNo: "23/ASD07/423",
    college: "ENG",
    department: "CIVIL ENG",
    email: "duc@un.kp",
  },
  {
    id: 2,
    firstName: "Francis",
    lastName: "Cummings",
    matricNo: "23/ASD07/423",
    college: "ENG",
    department: "CIVIL ENG",
    email: "nav@vaczez.br",
  },
  {
    id: 3,
    firstName: "Sylvia",
    lastName: "Rogers",
    matricNo: "23/ASD07/423",
    college: "ENG",
    department: "CIVIL ENG",
    email: "tas@pimehbut.sm",
  },
  {
    id: 4,
    firstName: "Tyler",
    lastName: "McDonald",
    matricNo: "23/ASD07/423",
    college: "ENG",
    department: "CIVIL ENG",
    email: "lajoseca@as.je",
  },
  {
    id: 5,
    firstName: "Sadie",
    lastName: "Bell",
    matricNo: "23/ASD07/423",
    college: "ENG",
    department: "CIVIL ENG",
    email: "vo@timec.pm",
  },
  {
    id: 6,
    firstName: "Janie",
    lastName: "Valdez",
    matricNo: "23/ASD07/423",
    college: "ENG",
    department: "CIVIL ENG",
    email: "na@we.tg",
  },
  {
    id: 7,
    firstName: "Carlos",
    lastName: "Ortiz",
    matricNo: "23/ASD07/423",
    college: "ENG",
    department: "CIVIL ENG",
    email: "piudde@rumged.co",
  },
];

export default data;
